// micro-app/micro-react/src/App.jsx
// import {useState} from "react";

const App = () => {

    const [count, setCount]  = React.useState(0);
    const [vueCount, setVueCount] = React.useState(0);
    React.useEffect(()=>{
            window.listener.call("reactCount",count);
    },[count]);

    React.useEffect(() => {
        window.listener.tap('vueCount',(args)=>{
            setVueCount(args);
        })
    },[vueCount])
    return (
        <>
            <h1>React:{count}</h1>
            <button onClick={()=>{setCount(count + 1)}}> + </button>
            <button onClick={()=>{setCount(count - 1)}}> - </button>
            <h2>Vue的点击次数：{vueCount}</h2>
        </>
    )
}
export default App;

// micro-app/micro-vue/src/App.vue
<template>
    <div>
        <h1>Vue:{{count}}</h1>
        <button @click="addCount">+</button>
        <button @click="redCount">-</button>
        <h2>React的点击次数：{{reactCount}}</h2>
    </div>
</template>
<script>
export default {
    data(){
        return {
            count: 0,
            reactCount: 0,
        }
    },
    methods: {
        addCount(){
            this.count++;
        },
        redCount(){
            this.count--;
        }
    },
    created(){
        let _self =this;
        window.listener.tap('reactCount',(arg)=> {
            _self.reactCount = arg;
        })
    },
    watch: {
        count(){
            window.listener.call('vueCount',this.count);
        }
    }
}
</script>
